//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
